#!/usr/bin/env perl
$lualatex     = 'lualatex -shell-escape -synctex=1 -interaction=nonstopmode';
$latex = 'platex -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %O %S';
$pdflualatex  = $lualatex;
$biber = 'biber --bblencoding=utf8 -u -U --output_safechars %O %S';
$bibtex = 'pbibtex %O %S';
$makeindex = 'mendex %O -o %D %S';
$dvipdf = 'dvipdfmx %O -o %D %S';

$max_repeat = 5;
$pdf_mode = 4;
$pvc_view_file_via_temporary = 0;
$pdf_previewer    = "open -ga /Applications/Skim.app";
