import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

# ====================== SHELL ======================

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij attach --index 0 --create"]

# ====================== WINDOW ======================
[window]

# Enable to use Alt key
option_as_alt = "Both"

# Opacity
opacity = 0.85  # Default: 1.0

# Window title
title = "Alacritty"  # Default: "Alacritty"

# ====================== SCROLING ======================
[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3

# ====================== FONT ======================
[font]

# Normal font style
normal = { family = "Hack Nerd Font Mono", style = "Regular" }  # Default for Linux/BSD:

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 13  # Default: 11.25

# ====================== COLORS ======================
[colors]
indexed_colors = [] # Default

# Transparent background colors
transparent_background_colors = false  # Default

# Draw bold text with bright colors
draw_bold_text_with_bright_colors = false  # Default

# ====================== CURSOR ======================
[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 750  # Default: 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 5  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15
